### ISSUE TITLE
Show attachments within investigation prompts and reports

### ISSUE THREAD

**Issue by Jasius** [Microsoft-community/Dotsimus#135]

**Comment by KojiOdyssey** [comment]
### Working on this.
#### Current state:
![image](https://user-images.githubusercontent.com/90523357/134101000-ef04244d-7be2-448e-a5a5-537c307b9647.png)

#### TODO:
- Implement for investigations
- Don't create an embed when the file doesn't display in a thumbnail
- Polish the embeds

#### When reporting undisplay able attachments:
![image](https://user-images.githubusercontent.com/90523357/134101232-eb2c4368-a807-4bfd-b3f4-7ee85dbda158.png)

**Comment by Jasius** [comment]
Completed by @KojiOdyssey
