### ISSUE TITLE
Watch functionality regressions

### ISSUE THREAD

**Issue by Jasius** [Microsoft-community/Dotsimus#138]
- [x] #140
![image](https://user-images.githubusercontent.com/11031051/133908957-89673f1e-4614-46c3-9033-9f21fc32b7f5.png)

- [x] #139
![image](https://user-images.githubusercontent.com/11031051/133908988-ec02f58b-62f0-40eb-8430-315bcc9d1e6a.png)

- [x] #141

**Comment by itsWindows11** [comment]
I already done the last one (idk if I should make a PR or not) but as far as I know, @KojiOdyssey is working on them so I don't want duplicate PRs

**Comment by Jasius** [comment]
> I already done the last one (idk if I should make a PR or not) but as far as I know, @KojiOdyssey is working on them so I don't want duplicate PRs

Just make a PR, it's a relatively simple change so Koji shouldn't have any issues solving a merge conflict if they already made this change.

**Comment by itsWindows11** [comment]
> > I already done the last one (idk if I should make a PR or not) but as far as I know, @KojiOdyssey is working on them so I don't want duplicate PRs
> 
> Just make a PR, it's a relatively simple change so Koji shouldn't have any issues solving a merge conflict if they already made this change.

Then fine, I will work on it tomorrow!
