### ISSUE TITLE
Poll result owner field is buggy when user has a hyphen in their user tag

### ISSUE THREAD

**Issue by itsWindows11** [Microsoft-community/Dotsimus#188]
Actual behavior:
![image](https://user-images.githubusercontent.com/81253203/141613478-eb8ea4d3-8f6a-4027-88a3-bbfcc2bbc636.JPG)

Expected behavior: it should show the user ID with a mention even if the user has a hyphen in their user tag.

**Comment by Jasius** [comment]
closed by #189
