### ISSUE TITLE
Consideration of negation

### ISSUE THREAD

**Issue by FJduFou** [Microsoft-community/Dotsimus#48]
I have test this in first:
```
!toxic testuser is not a fool, nor is he a fucker
I am 76.40% certain that this is a negative message.
```

And to understand the system, I performed some tests
```
!toxic fool fucker suck
I am 91.91% certain that this is a negative message.

!toxic no don't never
I am 3.20% certain that this is a negative message.

!toxic love like
I am 1.19% certain that this is a negative message.

!toxic love fuck
I am 67.93% certain that this is a negative message.
```

I thus deduce that the words have a value, and according to this one, it gives a result (with the negative words [therefore with greater value] are "priorities") but it does not take into account the negations which cancel the unfortunately meaning of negation...

Would it be possible to take into consideration the negations so that the words "priorities" are reduced?
If you don't understand, I can explain myself again ...

**Comment by Jasius** [comment]
Hey,

I do agree that toxicity rating shouldn't be this high for this query, insult probability rates even worse in this case.
![image](https://user-images.githubusercontent.com/11031051/101244375-d8b8ed80-370e-11eb-8e4b-b686ebdc4778.png)

As of right now on MS community to counteract false positives bot looks up whether user is new or not and if they're new and their first message is something that bot treats as egregious the user gets instantly muted. All other users get treated by their last two messages which helps to avoid false positives significantly. 
![image](https://user-images.githubusercontent.com/11031051/101244486-80ceb680-370f-11eb-8a1d-b09e26091434.png)

Also, server moderators can submit feedback to machine learning model with `sendfeedback` command which helps to tweak the model.

**Comment by FJduFou** [comment]
> Also, server moderators can submit feedback to machine learning model with command which helps to tweak the model.`sendfeedback`

I'm not moderator 😄 

> As of right now on MS community to counteract false positives bot looks up whether user is new or not and if they're new and their first message is something that bot treats as egregious the user gets instantly muted. All other users get treated by their last two messages which helps to avoid false positives significantly.

It still doesn't take into account the use of the "don't" (for example [what I call the negation]) which cancels the insult ...

**Example:** Do not insult and do not piss off testuser
Here, the "don't" (or equivalent) comes to counter the insult

**Comment by Jasius** [comment]
> It still doesn't take into account the use of the "don't" (for example [what I call the negation]) which cancels the insult

Yes you're right about this, it doesn't and that's why bot should be fed feedback about incorrect cases to reduce amount of false positives, it's not something that can be fixed easily.

**Comment by FJduFou** [comment]
> Yes you're right about this, it doesn't and that's why bot should be fed feedback about incorrect cases to reduce amount of false positives, it's not something that can be fixed easily.

Yes, but if it's really functional then that would be wonderful ... and I dream that everything works as well as possible...
Could you add 2 reactions for example so that the user can validate or report: an `:white_check_mark:` and a `:warning:` (the `:warning:` required verification with trusted people and and prohibit people who are below Tiers2 to react for example)?
> **Machine learning powered** chat moderation bot. 😄

**Comment by Jasius** [comment]
That's one of the ideas that I have in my mind but it is not a priority as of right now, thank you for the suggestion and feedback!

**Comment by FJduFou** [comment]
No problem, I'll wait
