### ISSUE TITLE
Flags french as a swear because ofc it does.

### ISSUE THREAD

**Issue by TheFarmingBunny** [Microsoft-community/Dotsimus#6]
![image](https://user-images.githubusercontent.com/17672664/90814467-0c6b3580-e321-11ea-9891-fdf66e9a4514.png)

**Comment by Jasius** [comment]
Im not entirely sure why this emoji combo in particular triggers this reaction but I'll strip out unicode emojis for now from the messages
![image](https://user-images.githubusercontent.com/11031051/90815294-2877d280-e333-11ea-9c7a-8576f4d778ff.png)
