### ISSUE TITLE
Polling functionality

### ISSUE THREAD

**Issue by Jasius** [Microsoft-community/Dotsimus#80]
## Functionality/Features

- [ ] There can't be more than 5 polls running in the same server, maybe limit could be higher for premium as probability of abuse is lower.

- [ ] DM user who initiated the poll once it ends.

- [ ] DM users who voted on the poll once it ends, make sure to account for rate limitations, DM in batches rather than try to DM everyone at once.

- [ ] Ability to cancel, remove the pool by poll creator or moderation(i.e anyone with kick/ban perms).

- [ ] Max duration should be 7 days(at least for now)

- [ ] Max options limit should be set as 9 for now and votes would be done with number emojis(i.e 1️⃣2️⃣3️⃣)

- [ ] Show first 5 people who voted, it should look like this - @name, @name and 12 other users voted.

## General support

- [ ] If bot restarts it should be able to recover the poll session, I suppose storing poll information in a local file for recovery would work, database usage would be excessive in this case.

## Stretch goals

- [ ] Give an option between private and public polls, private option wouldn't show votes up until the poll ends, public one would show them as people vote. 

- [ ] Poll creator should be sent a CSV file that would contain the list of voters and their votes. 

- [ ] Ability to choose between single vote and multi-option poll. I.e single vote would only allow user to vote on one option, voting again would remove their previous vote.

Owner: @SapphireVideos

**Comment by SapphireVideos** [comment]
Most of the command is done. I will finish soon probably.

**Comment by gamerboy80** [comment]
> 
> 
> Most of the command is done. I will finish soon probably.

hes never gonna finish it

**Comment by Jasius** [comment]
@gamerboy80 you know that issue watchers get notification then moment you comment :)?

**Comment by gamerboy80** [comment]
Yes

**Comment by Jasius** [comment]
> Most of the command is done. I will finish soon probably.

Hey, are you still working on this?

**Comment by SapphireVideos** [comment]
I was learning some more stuff. I was stuck without idea of what to do. Now I kinda have an idea of how to do it.

**Comment by SapphireVideos** [comment]
nvm this didnt work
